### PR TITLE
Fix build issues

### LINKED ISSUE #40: Failure to build with notify 5.0.0-pre.11
It was working file with notify 5.0.0-pre.10, but with .11 I get:

```
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/linemux-0.2.2/src/events.rs:62:64
   |
62 |         let inner: notify::RecommendedWatcher = NotifyWatcher::new_immediate(move |res| {
   |                                                                ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`
```

### PR DESCRIPTION
**Pull request by Alexei-Barnes**
This simply addresses the build issues after the changes to the beta version of notify this is using.
Fixes #40

### CODE REVIEW

**Comment by jmagnuson** [comment]
Thank you!

Would you mind also bumping the `notify` entry in `Cargo.toml` to the latest? This change will make all previous versions incompatible.

Could you also add a CHANGELOG entry? Something simple is fine, like 

```
### Fixed
- Update `notify` to `5.0.0-pre.11` to fix build errors
```

Edit: I've got a little bit of time to do a release this weekend, so went ahead and added the above to get this merged.

**Comment by Alexei-Barnes** [comment]
Beat me to it, sorry :) Been a busy few days at work recently so I didn't find much time to look at open source work 😅
Thanks for the great tool by the way, this library saved me several hours trying to do this myself on a weekend.

**Comment by Alexei-Barnes** [comment]
Looking at this change again, perhaps it should have been `watch<P: AsRef<Path>>(...)`? That appears to be what the standard library does. I'm not actually sure why doing it as a generic over `AsRef<Path>` is or is not better than simply `&Path`, but I imagine there is a good reason the standard library does it that way.
