### ISSUE TITLE
Failure to build with notify 5.0.0-pre.11

### ISSUE THREAD

**Issue by ndmitchell** [jmagnuson/linemux#40]
It was working file with notify 5.0.0-pre.10, but with .11 I get:

```
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/linemux-0.2.2/src/events.rs:62:64
   |
62 |         let inner: notify::RecommendedWatcher = NotifyWatcher::new_immediate(move |res| {
   |                                                                ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`
```

**Comment by jmagnuson** [comment]
Thanks! Yeah, notify's `Watcher` API changed in https://github.com/notify-rs/notify/pull/336. I've been looking forward to this change for a while, so will get a corresponding linemux release out soon.

Edit: looks like @Alexei-Barnes might be tackling it? If so, thanks!

**Comment by Alexei-Barnes** [comment]
I've been noticed!
Yea I needed this and the build issues were easy enough to fix. I'll make a PR.

**Comment by jmagnuson** [comment]
linemux [0.2.3](https://crates.io/crates/linemux/0.2.3) has been published to crates.io!
