### PR TITLE
Update notify pre11

### LINKED ISSUE #40: Failure to build with notify 5.0.0-pre.11
It was working file with notify 5.0.0-pre.10, but with .11 I get:

```
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/linemux-0.2.2/src/events.rs:62:64
   |
62 |         let inner: notify::RecommendedWatcher = NotifyWatcher::new_immediate(move |res| {
   |                                                                ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`
```

### PR DESCRIPTION
**Pull request by jmagnuson**
Fixes #40.

### CODE REVIEW

**Comment by jmagnuson** [comment]
Superseded by #42.
